### ISSUE TITLE
Vision of this Framework

### ISSUE THREAD

**Issue by enociz** [codebrendon/nex-css-framework#1]
Where does the community and @codebrendon see this framework in the future? What will make it different from the immense plethora of frameworks out there already?

**Comment by codebrendon** [comment]
This is more as a learning experience for the people who want to learn things like project work flow, contributing on a open source project, and all kinds of things. This is more than a framework its learning experience. :)

**Comment by enociz** [comment]
I see, how do you plan to involve that?

I'm guessing that things like file structuring, project organisation, tips and tricks etc, will be the focus in the teaching part.
